// SPDX-License-Identifier: GPL-2.0

//! Netfilter bindings and safe wrappers.
//!
//! This module provides safe Rust abstractions over the Linux kernel's
//! netfilter subsystem, including hook registration and response types.

use kernel::prelude::*;
use core::cell::UnsafeCell;
use core::marker::PhantomPinned;
use core::pin::Pin;

use crate::skbuff::SkBuff;

// FFI bindings — these would be generated by bindgen in a real kernel build.
// For now we define the necessary constants and types manually.

/// Raw netfilter constants (equivalent to C #defines).
pub(crate) mod raw {
    pub const NF_DROP: u32 = 0;
    pub const NF_ACCEPT: u32 = 1;
    pub const NF_STOLEN: u32 = 2;
    pub const NF_QUEUE: u32 = 3;
    pub const NF_REPEAT: u32 = 4;
    pub const NF_STOP: u32 = 5;

    pub const NFPROTO_INET: u32 = 1;
    pub const NFPROTO_IPV4: u32 = 2;
    pub const NFPROTO_IPV6: u32 = 10;

    pub const NF_INET_PRE_ROUTING: u32 = 0;
    pub const NF_INET_LOCAL_IN: u32 = 1;
    pub const NF_INET_FORWARD: u32 = 2;
    pub const NF_INET_LOCAL_OUT: u32 = 3;
    pub const NF_INET_POST_ROUTING: u32 = 4;
}

/// Responses from hook functions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum HookResponse {
    /// Drop the packet.
    Drop = raw::NF_DROP as _,
    /// Accept the packet.
    Accept = raw::NF_ACCEPT as _,
    /// Packet has been "stolen" or consumed by the hook function.
    Stolen = raw::NF_STOLEN as _,
    /// Queue the packet to userspace for processing.
    Queue = raw::NF_QUEUE as _,
    /// Run the current hook function again.
    Repeat = raw::NF_REPEAT as _,
    #[deprecated(note = "Deprecated, for userspace nf_queue compatibility.")]
    /// Stop processing.
    Stop = raw::NF_STOP as _,
}

impl HookResponse {
    /// The highest possible verdict number.
    #[allow(deprecated)]
    pub(crate) const MAX_VERDICT: HookResponse = HookResponse::Stop;

    /// Convert to raw unsigned integer for kernel FFI.
    pub(crate) fn as_u32(self) -> u32 {
        self as u32
    }
}

/// Protocol family for netfilter hooks.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ProtocolFamily {
    /// Internet (both IPv4 and IPv6).
    Inet,
    /// IPv4 only.
    Ipv4,
    /// IPv6 only.
    Ipv6,
}

impl ProtocolFamily {
    /// Convert to raw kernel constant.
    pub(crate) fn as_u32(self) -> u32 {
        match self {
            Self::Inet => raw::NFPROTO_INET,
            Self::Ipv4 => raw::NFPROTO_IPV4,
            Self::Ipv6 => raw::NFPROTO_IPV6,
        }
    }
}

/// Hook number (where in the network stack to intercept).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum HookNumber {
    /// Before routing decision.
    PreRouting,
    /// Packet destined for local process.
    LocalIn,
    /// Packet being forwarded.
    Forward,
    /// Packet generated by local process.
    LocalOut,
    /// After routing decision, before transmission.
    PostRouting,
}

impl HookNumber {
    /// Convert to raw kernel constant.
    pub(crate) fn as_u32(self) -> u32 {
        match self {
            Self::PreRouting => raw::NF_INET_PRE_ROUTING,
            Self::LocalIn => raw::NF_INET_LOCAL_IN,
            Self::Forward => raw::NF_INET_FORWARD,
            Self::LocalOut => raw::NF_INET_LOCAL_OUT,
            Self::PostRouting => raw::NF_INET_POST_ROUTING,
        }
    }
}

/// Represents the kernel's `struct nf_hook_ops`.
///
/// This is an opaque wrapper around the raw kernel structure.
#[repr(C)]
pub(crate) struct NfHookOps {
    /// Hook callback function pointer.
    hook: Option<unsafe extern "C" fn(*mut core::ffi::c_void, *const core::ffi::c_void, *const core::ffi::c_void) -> u32>,
    /// Protocol family.
    pf: u32,
    /// Hook number.
    hooknum: u32,
    /// Priority.
    priority: i32,
}

/// Safe wrapper around netfilter hook operations.
///
/// Manages the lifecycle of a netfilter hook registration.
pub(crate) struct NetFilterHookOps {
    /// The underlying hook ops structure.
    ops: UnsafeCell<NfHookOps>,
    /// The user-provided hook function.
    hook_fn: fn(&SkBuff) -> HookResponse,
    /// Whether this hook is currently registered.
    registered: bool,
    /// Pin marker.
    _pin: PhantomPinned,
}

// SAFETY: NetFilterHookOps is only accessed from the kernel context where
// the hook is registered. The kernel ensures proper synchronization.
unsafe impl Send for NetFilterHookOps {}
unsafe impl Sync for NetFilterHookOps {}

impl NetFilterHookOps {
    /// Create a new netfilter hook operation (unregistered).
    ///
    /// # Arguments
    ///
    /// * `hook_fn` - The callback function to invoke for each packet.
    /// * `pf` - Protocol family to filter.
    /// * `hooknum` - Where in the network stack to intercept.
    /// * `priority` - Hook priority (lower = earlier).
    pub(crate) fn new(
        hook_fn: fn(&SkBuff) -> HookResponse,
        pf: ProtocolFamily,
        hooknum: HookNumber,
        priority: i32,
    ) -> Result<Pin<Box<Self>>> {
        let ops = NfHookOps {
            hook: Some(Self::nf_hook_callback),
            pf: pf.as_u32(),
            hooknum: hooknum.as_u32(),
            priority,
        };

        let hook_ops = Self {
            ops: UnsafeCell::new(ops),
            hook_fn,
            registered: false,
            _pin: PhantomPinned,
        };

        // SAFETY: We pin the value immediately and never move it.
        let pinned = Box::pin(hook_ops);
        Ok(pinned)
    }

    /// Register the hook with the kernel's netfilter subsystem.
    ///
    /// After this call, the hook function will be invoked for matching packets.
    pub(crate) fn register(mut self: Pin<Box<Self>>) -> Result<Pin<Box<Self>>> {
        // SAFETY: We call the kernel's nf_register_net_hook function.
        // The hook_ops structure must remain pinned for the duration of registration.
        unsafe {
            let self_mut = Pin::get_unchecked_mut(self.as_mut());
            // In a real kernel build, this would call:
            // bindings::nf_register_net_hook(&bindings::init_net, self_mut.ops.get());
            self_mut.registered = true;
        }
        pr_info!("Netfilter hook registered\n");
        Ok(self)
    }

    /// Unregister the hook from the kernel's netfilter subsystem.
    fn unregister(&mut self) {
        if self.registered {
            // SAFETY: We call the kernel's nf_unregister_net_hook function.
            // In a real kernel build, this would call:
            // unsafe { bindings::nf_unregister_net_hook(&bindings::init_net, self.ops.get()); }
            self.registered = false;
            pr_info!("Netfilter hook unregistered\n");
        }
    }

    /// The raw C-compatible callback that the kernel invokes.
    ///
    /// # Safety
    ///
    /// This function is called by the kernel's netfilter subsystem. The caller
    /// must provide valid pointers to the hook state and sk_buff.
    unsafe extern "C" fn nf_hook_callback(
        _priv_data: *mut core::ffi::c_void,
        skb_ptr: *const core::ffi::c_void,
        _state: *const core::ffi::c_void,
    ) -> u32 {
        // SAFETY: The kernel guarantees skb_ptr is a valid pointer to sk_buff
        // for the duration of this callback.
        let skb = unsafe { SkBuff::from_ptr(skb_ptr as *const _) };

        // We need to recover our hook_fn. In a real implementation, _priv_data
        // would point to our NetFilterHookOps instance.
        // For this example, we call the module-level hook function directly.
        let response = crate::hook_func(skb);
        response.as_u32()
    }
}

impl Drop for NetFilterHookOps {
    fn drop(&mut self) {
        self.unregister();
    }
}
