// SPDX-License-Identifier: GPL-2.0

//! Safe wrapper around the kernel's `struct sk_buff`.
//!
//! `sk_buff` is the primary metadata structure for network packets in the
//! Linux kernel. This module provides a safe Rust abstraction over it.

use core::cell::UnsafeCell;

/// Placeholder for the raw sk_buff structure that would be generated by bindgen.
/// In a real kernel build, this comes from the generated bindings.
#[repr(C)]
pub(crate) struct sk_buff {
    // Network header offset
    pub network_header: u16,
    // Transport header offset
    pub transport_header: u16,
    // Pointer to packet data
    pub data: *const u8,
    // Total packet length
    pub len: u32,
    // Data length (in fragments)
    pub data_len: u32,
    // Protocol (ETH_P_IP, etc.)
    pub protocol: u16,
}

/// Safe wrapper around the kernel's `struct sk_buff`.
///
/// This type uses `#[repr(transparent)]` to ensure it has the exact same
/// memory layout as `sk_buff`, allowing safe pointer casts.
#[repr(transparent)]
pub(crate) struct SkBuff(UnsafeCell<sk_buff>);

// SAFETY: SkBuff is accessed only via shared references obtained from
// kernel-provided pointers during hook callbacks. The kernel guarantees
// the sk_buff is valid for the duration of the callback.
unsafe impl Sync for SkBuff {}

impl SkBuff {
    /// Creates a reference to [`SkBuff`] from a valid pointer.
    ///
    /// # Safety
    ///
    /// The caller must ensure that `ptr` is valid and will remain valid for
    /// the lifetime of the returned [`SkBuff`] reference.
    pub(crate) unsafe fn from_ptr<'a>(ptr: *const sk_buff) -> &'a SkBuff {
        // SAFETY: Safety requirements guarantee the validity of the dereference,
        // while the SkBuff type being transparent makes the cast ok.
        unsafe { &*ptr.cast() }
    }

    /// Get a pointer to the underlying sk_buff data.
    fn inner(&self) -> &sk_buff {
        // SAFETY: We only read from the sk_buff during hook callbacks where
        // the kernel guarantees validity.
        unsafe { &*self.0.get() }
    }

    /// Get the raw packet data as a byte slice.
    pub(crate) fn data(&self) -> &[u8] {
        let inner = self.inner();
        let len = self.len();
        // SAFETY: The kernel guarantees data points to valid memory of at least
        // `len` bytes during the hook callback.
        unsafe { core::slice::from_raw_parts(inner.data, len) }
    }

    /// Get the total length of the packet (linear + fragments).
    pub(crate) fn len(&self) -> usize {
        self.inner().len as usize
    }

    /// Get a pointer to the network header (e.g., IP header).
    pub(crate) fn network_header(&self) -> *const u8 {
        let inner = self.inner();
        // SAFETY: network_header is an offset from head pointer.
        // In the simplified version, we compute from data.
        unsafe { inner.data.add(inner.network_header as usize) }
    }

    /// Get a pointer to the transport header (e.g., TCP/UDP header).
    pub(crate) fn transport_header(&self) -> *const u8 {
        let inner = self.inner();
        // SAFETY: transport_header is an offset from head pointer.
        unsafe { inner.data.add(inner.transport_header as usize) }
    }

    /// Get the EtherType protocol field.
    pub(crate) fn protocol(&self) -> u16 {
        self.inner().protocol
    }
}
